### ISSUE TITLE
update to latest stencil?

### ISSUE THREAD

**Issue by sardeenz** [Dzeneralen/esri-stencil-example#1]
Can you try updating to the latest version of stencil? I think it's a 1.0.7 now? I'm fighting an error Rollup: Missing Export
'loadModules' is not exported by node_modules/esri-loader/dist/umd/esri-loader.js

Looks like other stencil users trying to work with third party libraries are having similar issues - outlined here - https://github.com/ionic-team/stencil/issues/1343 

My test example component (that is throwing the above error) is here - https://github.com/CORaleigh/chf-stencil-component.git and it's quite possible that I'm just doing something wrong. Any assistance is appreciated, would love to have this working and be comfortable with it before the UC.

**Comment by Dzeneralen** [comment]
Updated to Stencil 1.0.1 as that is where the router version stopped. When updating core and leaving router it stopped working. Deleted the spec files too as the API had changed a lot from what it used to be, but I got the application up and running now.

**Comment by Dzeneralen** [comment]
The fix to the issue you were having was what you were pointing out in ionic-team/stencil#1343, check the stencil.config.ts for how to get it working. Closing the issue as it seems to be resolved :)
